using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace TileBar_from_code.View
{
    /// <summary>
    /// Interaction logic for SubCategory1View.xaml
    /// </summary>
    public partial class SubCategory1View : UserControl
    {
        public SubCategory1View()
        {
            InitializeComponent();
        }

        private void GridControl_AutoGeneratedColumns(object sender, RoutedEventArgs e)
        {

        }
    }
}
